name       : pyxdg
version    : '0.26'
release    : 7
source     :
    - https://files.pythonhosted.org/packages/47/6e/311d5f22e2b76381719b5d0c6e9dc39cd33999adae67db71d7279a6d70f4/pyxdg-0.26.tar.gz : fe2928d3f532ed32b39c32a482b54136fe766d19936afc96c8f00645f9da1a06
license    : GPL-2.0-or-later
component  : programming.python
summary    : Python XDG Module
description: |
    PyXDG is a python library to access freedesktop.org standards.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
