name       : pyxdg
version    : '0.27'
release    : 9
source     :
    - https://files.pythonhosted.org/packages/6f/2e/2251b5ae2f003d865beef79c8fcd517e907ed6a69f58c32403cec3eba9b2/pyxdg-0.27.tar.gz : 80bd93aae5ed82435f20462ea0208fb198d8eec262e831ee06ce9ddb6b91c5a5
license    : GPL-2.0-or-later
component  : programming.python
summary    : Python XDG Module
description: |
    PyXDG is a python library to access freedesktop.org standards.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
