name       : pyxdg
version    : 0.25
release    : 5
source     :
    - https://pypi.python.org/packages/source/p/pyxdg/pyxdg-0.25.tar.gz : 81e883e0b9517d624e8b0499eb267b82a815c0b7146d5269f364988ae031279d
license    : GPL-2.0
component  : programming.python
summary    : Python XDG Module
description: |
    Python XDG Module
builddeps  :
    - pkgconfig(python3)
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2014-1624.patch
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
