name       : pyxdg
version    : '0.27'
release    : 12
source     :
    - https://pypi.io/packages/source/p/pyxdg/pyxdg-0.27.tar.gz : 80bd93aae5ed82435f20462ea0208fb198d8eec262e831ee06ce9ddb6b91c5a5
license    : GPL-2.0-or-later
component  : programming.python
summary    : Python XDG Module
description: |
    PyXDG is a python library to access freedesktop.org standards.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
