name       : pyxdg
version    : 0.25
release    : 4
source     :
    - https://pypi.python.org/packages/source/p/pyxdg/pyxdg-0.25.tar.gz : 81e883e0b9517d624e8b0499eb267b82a815c0b7146d5269f364988ae031279d
license    : GPL-2.0
summary    : Python XDG Module
description: |
    Python XDG Module
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
setup      : |
build      : |
    %patch -p1 < $pkgfiles/security/cve-2014-1624.patch
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
